version: '3.3'
services: 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app